### ISSUE TITLE
Missing kbin communities?

### ISSUE THREAD

**Issue by csm10495** [tgxn/lemmy-explorer#100]
Hey folks,

I searched for "squaredcircle" and got: 

![image](https://github.com/tgxn/lemmy-explorer/assets/5749838/7672529c-444f-41ab-9324-d83c731134d4)

This seems to be missing the SquaredCircle community on kbin: https://sh.itjust.works/c/SquaredCircle@kbin.social. 

Any idea why it didn't pop up? I have 'selected all' instances. Do kbin communities not show up?

**Comment by tgxn** [comment]
Cause I only currently scan instances from `lemmy` instances :)

I'll take this as a feature request to scan KBin magazines too - but this will require mre effort (since I need to write an implementation that gets the same details as Lemmy returns) and then format it for display on the frontend.

Probably a couple days, but no promises. 🤞

**Comment by tgxn** [comment]
Notes on what I'm thinking:
- KBin magazines will be hidden by default, and I'll have a menu option to display them.

Also, quick checking none of the KBin APIs work ? I'm getting errors from everything, maybe something I'm doing wrong
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/b25c4fe6-b17e-4b6b-804e-21e3cb71988d)
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/5108ea67-3de9-49c9-b86b-42d8c17ffa1e)
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/18fe226a-09b6-4ab8-9223-c68258169071)

I'm looking at the docs here
https://docs.kbin.pub/#get-single-magazine


kbin.social/m/SquaredCircle

**Comment by tgxn** [comment]
OK this works
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/1960579c-ad74-4b5b-b9f6-a590fbff98f2)

**Comment by csm10495** [comment]
Ayee there ya go. I would recommend going the other direction and having kbin ones be included by defaults and opt-out able. 

At the end of the day: fediverse is fediverse and cross-pollination between lemmy and kbin should work out just fine. My other qualm is that I personally have missed out on communities from barely knowing what kbin was. I don't think regular users should care or know the difference.

(At the end of the day, your choice though) :)

**Comment by tgxn** [comment]
Still an issue, that the endpoints to returns **lists** of magazines don't seem to work :/ Which would stop me crawling for any communities.


> At the end of the day: fediverse is fediverse and cross-pollination between lemmy and kbin should work out just fine. My other qualm is that I personally have missed out on communities from barely knowing what kbin was. I don't think regular users should care or know the difference.

Yeah I don't really disagree, I was more trying to make it simpler for new users;
I think as long as I can differentiate the view (like the card could be purple or something and clearly say it's a KBin community) then that should be ok to include by default.

**Comment by tgxn** [comment]
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/17e381a0-a10c-4d11-9e75-b552a8c13eeb)
Just running into roadblocks with kbin's API 😠

**Comment by csm10495** [comment]
Yeah.. i'm really confused as to how federation works. Like I thought somehow Lemmy/Kbin would have similar APIs for communities, but yeah, I can't seem to find any way to get their magazine list api to work.

**Comment by tgxn** [comment]
Super frustrating, looks like they have some work on new APIs here: https://codeberg.org/Kbin/kbin-core/pulls/357

**Comment by csm10495** [comment]
Here is a 'terrible' way to get all the magazines on a given kbin instance:

```
#!/bin/bash
# Parses all kbin magazines listed on a given instance
# Pass the results to 'grep -v @' to filter out magazines on other instances

INSTANCE=$1

if [ -z $INSTANCE ]; then
    echo "Provide an instance as the only parameter (like kbin.social)"
    exit 1
fi

function parse() {
    PAGE=$1
    curl --fail -s https://${INSTANCE}/magazines?p=$PAGE | grep form | grep '/subscribe' | sed 's/.*="\/m\/\(.*\)\/subscribe"/\1/g'
    return ${PIPESTATUS[0]}
}

for idx in $(seq 10000); do
    if ! parse $idx; then
        break
    fi
done
```

Basically it walks the magazines list html and parses for /subscribe then pulls out the magazine name. It takes about a minute or so.. but I'm not sure its a great way to handle this.

Here's a current list it pulled (sort/uniq'd) via:

```
./scrape_kbin_communities.sh kbin.social | sort | uniq > kbin.social_communities.txt
```
[kbin.social_communities.txt](https://github.com/tgxn/lemmy-explorer/files/11933806/kbin.social_communities.txt)

**Comment by tgxn** [comment]
Getting somewhere now! :D - Sketchy method I am not a huge fan of, I implemented it _**[directly](https://github.com/tgxn/lemmy-explorer/pull/101/commits/634e8ae1e83f76123a06989082f001eb64632393#diff-cd8cb757074242e341c7ceaf8ec0d2b0ab857897027dc87542394a07debb02f6)**_ lmao

![image](https://github.com/tgxn/lemmy-explorer/assets/293107/702d6abb-74e7-4cb6-a19f-7fb2d21323e2)

**Comment by tgxn** [comment]
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/e3da0144-76f0-4259-b784-bd80774371d0)

just deploying it now... 🤞

**Comment by csm10495** [comment]
Looks good! Thanks! Hopefully a real API works eventually lol.
