### ISSUE TITLE
Seems to miss some communities

### ISSUE THREAD

**Issue by Zamboniman** [tgxn/lemmy-explorer#105]
There seems to be some communities missing, and some of these were showing up previously.

One of these is !retrotechnology@lemmy.ca and another is !debateanatheist@lemmy.ca. 

Both of these examples were showing up previously, but are not showing up any more. For one of these, others have created a similar community on a different server at later dates than this one was created, and it's possible it not showing up anymore here may have contributed to this.

**Comment by tgxn** [comment]
Mornin mate, this seems to be an issue... i don't have data on debateanathiest, but retro got updated ~30 mins ago on my side.
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/1420e822-2956-4916-a846-fe57863a2e32)

![image](https://github.com/tgxn/lemmy-explorer/assets/293107/bdbe72cd-3716-46c6-83d7-0e900d24031f)


I am currently working through a change to the UI to try and make it more performant now I'm seeing 26+ communities! 😅
So an update is likely to be pushed tonight or tomorrow that should resolve these issues...

As for `[debateanatheist@lemmy.ca](mailto:debateanatheist@lemmy.ca).` I forced a single crawl and it's been deleted?
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/467b41f4-9841-4f1e-aae9-a502f8093337)
https://lemmy.ca/c/debateanatheist
