### ISSUE TITLE
Bug: Newest crawl doesn't show all communities

### ISSUE THREAD

**Issue by M4rtineski** [tgxn/lemmy-explorer#107]
**Describe the bug**
After the newest crawl from 1 hour ago I don't see my community with 1k subscribers and some others

**To Reproduce**
1. Go to this link: https://lemmyverse.net/communities?query=artificial+intelligence
2. My community was top 3 or top 4 before the newest crawl. It should be top 2 after the newest crawl because I got a lot of new subscribers.

**Expected behavior**
It should show all communities.

**Additional context**
Including sus communities still didn't show my community when I suspected incorrect flagging my community as sus.
My community: https://lemmy.fmhy.ml/c/singularity
Other community that I can point out missing: https://lemmy.fmhy.ml/c/fosai@lemmy.world

**Comment by M4rtineski** [comment]
Just checked and my instance is turned on: 
![image](https://github.com/tgxn/lemmy-explorer/assets/137183342/af80bc7d-9ade-4af2-ad80-c9e86af1c653)

**Comment by zabadoh** [comment]
Same thing here.

!anime@lemmy.ml which is a /c with 5.77K subscribers, 299 posts, 1.7K comments doesn't show up on a search for "anime" communities.

**Comment by M4rtineski** [comment]
@zabadoh my communities started showing up again after a crawl from a day ago but from what I see this is still a problem, hopefully this gets resolved soon enough.

**Comment by M4rtineski** [comment]
@tgxn "It also happens if the site that is being scanned goes down/is detected as down:"

Ooooh! This must be the reason for why this was the case!

**Comment by zabadoh** [comment]
Okay https://lemmy.ml/c/anime is showing up now.

**Comment by tgxn** [comment]
> Ooooh! This must be the reason for why this was the case!

Yeah a lot of the big sites are under the pump right now, I'm expecting there to be less instability as we go forward.

I'll close this for now, if you notice anything else sus, please let me know :)
