### ISSUE TITLE
Feature: hide Cloudflare-protected instances

### ISSUE THREAD

**Issue by KaKi87** [tgxn/lemmy-explorer#108]
**What do you want to see?**
I would like to see a *Hide CloudFlare-protected* checkbox in both *Instances* & *Communities* sections.

**Additional context**
https://framagit.org/dCF/deCloudflare/-/blob/master/readme/en.md

---

Thanks

**Comment by tgxn** [comment]
I had a read and I have a couple thoughts:

I don't typically have/store IP addresses when hitting instances, I could potentially just flag instances that return "Cloudflare" headers, which I think it always does, that might be easier than matching and maintaining IP addresses.

My only gripe would be that bad actors may use this data to find "unprotected" instances, to potentially abuse. But I think that it would be beneficial to at least cache the server headers in case I could use other data in there.

**Comment by KaKi87** [comment]
> I don't typically have/store IP addresses when hitting instances

If you need that, here's stuff of mine that you can use : https://git.kaki87.net/KaKi87/userscripts/src/branch/master/_lib/isCloudflareDomain.js

> I could potentially just flag instances that return "Cloudflare" headers

I guess that works too, if you already need to send requests to these.
(Otherwise, my solution doesn't involve making requests to the instances themselves).

> bad actors may use this data to find "unprotected" instances, to potentially abuse

Instances don't need CloudFlare to protect themselves.
Meanwhile, I do need to avoid CloudFlare to protect myself (cf. what I linked), which is also why I created userscripts that flags CloudFlare-protected results from 3 search engines.

**Comment by tgxn** [comment]
I'm now recording response headers from the `/api/v3/site` request. 
This should be handy for both CF detection and detection of things like CORS settings.

Non-CF:
```
  "headers": {
        "server": "nginx",
        "date": "Sun, 16 Jul 2023 17:45:03 GMT",
        "content-type": "application/json",
        "transfer-encoding": "chunked",
        "connection": "close",
        "vary": "accept-encoding, Origin, Access-Control-Request-Method, Access-Control-Request-Headers",
        "access-control-expose-headers": "vary, content-type, content-encoding",
        "strict-transport-security": "max-age=63072000",
        "referrer-policy": "same-origin",
        "x-content-type-options": "nosniff",
        "x-frame-options": "DENY",
        "x-xss-protection": "1; mode=block",
        "access-control-allow-methods": "GET, POST, OPTIONS"
    },
```
CF:
```
"headers": {
        "date": "Mon, 17 Jul 2023 02:52:56 GMT",
        "content-type": "application/json",
        "transfer-encoding": "chunked",
        "connection": "close",
        "access-control-expose-headers": "content-type, content-encoding, vary",
        "vary": "accept-encoding, Origin, Access-Control-Request-Method, Access-Control-Request-Headers",
        "x-content-type-options": "nosniff",
        "x-frame-options": "SAMEORIGIN",
        "x-xss-protection": "1; mode=block",
        "cf-cache-status": "DYNAMIC",
        "report-to": "{\"endpoints\":[{\"url\":\"https:\\/\\/a.cloudflare.com\\/report\\/v3REDACTED\"}],\"group\":\"cf-nel\",\"max_age\":604800}",
        "nel": "{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}",
        "strict-transport-security": "max-age=15552000; includeSubDomains; preload",
        "server": "cloudflare",
        "cf-ray": "7e7f31149c8b2748-ADL",
        "alt-svc": "h3=\":443\"; ma=86400"
    },
```
(notice presence of `cf-*` headers)

**Comment by KaKi87** [comment]
Hello,
Is there an ETA on adding this feature to the front-end ?
Thanks

**Comment by KaKi87** [comment]
Excellent, thanks !
