### ISSUE TITLE
Feature: Allow URL parameter to pass in Home Instance

### ISSUE THREAD

**Issue by jacobhuck** [tgxn/lemmy-explorer#129]
**What do you want to see?**
I would like to link to lemmy-explorer but pass in a URL to set as a home instance.  This would allow lemmy instance admins to make links to lemmy-explorer for new users and make the community subscription process easier.  This may also help reduce confusion as to which instance they should be using to subscribe.

**Additional context**
Example:  lemmy.ml might add the following to their signup page:
-*Need help finding communities?  Try out [Lemmy-Explorer](https://lemmyverse.net/communities?home-instance=lemmy.ml)!*

**Comment by tgxn** [comment]
I like this idea :) Sounds good.

**Comment by tgxn** [comment]
done in dev

[`https://develop.lemmyverse.net/communities?home_url=lemmy.ml`](https://develop.lemmyverse.net/communities?home_url=lemmy.ml)
[`https://develop.lemmyverse.net/communities?home_url=kbin.social&home_type=kbin`](https://develop.lemmyverse.net/communities?home_url=kbin.social&home_type=kbin)
