### ISSUE TITLE
Feature: Show community icon instead of banner 

### ISSUE THREAD

**Issue by jfryton** [tgxn/lemmy-explorer#131]
**What do you want to see?**
For communities without a banner, display its community icon instead. 

**Additional context**
Many communities are opting not to use a banner due to the volume of vertical space they take up and the fact that they aren't typically visible from various Lemmy apps.

**Comment by tgxn** [comment]
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/a8a819da-2bda-4dc3-a085-ec98349c18d0)
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/690f1b19-941e-42f7-be97-3d59fd86eb67)

looks so much nicer 😍

**Comment by tgxn** [comment]
I'll remove the "hide no banner" functionality too, it's silly now anyway
