### ISSUE TITLE
Feature: API layer for direct App integration

### ISSUE THREAD

**Issue by Fmstrat** [tgxn/lemmy-explorer#137]
**What do you want to see?**
Context: I'm a supporting developer on Thunder.

I'd love to see an API layer for search, so that Apps like Thunder can tap into this project for their community "all" search without a separate Redis instance in the cloud.

**Additional context**
API should return in JSON with basic name info, but should include the format of `community@instance.tld`. This will make subscribing pass-through easy on devs.

**Comment by tgxn** [comment]
https://data.lemmyverse.net/
are any of these dumps suitable?

what would your ideal data format be, you're more than welcome to run post-processors over my data, or let me know what data format you'd like to see.

**Comment by tgxn** [comment]
I had a think about this and posted some things here https://github.com/thunder-app/thunder/issues/508#issuecomment-1667485426

I am thinking I could write a Dockerfile that includes something like Meilisearch-based docker image with the Lemmyverse data pre-loaded or something. 🤔

I really don't want to have to host anything other than static files, so people would still need to host this themselves.

**Comment by tgxn** [comment]
I'm going to close this, LMK if they need more changes to implement their functionality :)
