### ISSUE TITLE
Feature: Sort communities in instances view

### ISSUE THREAD

**Issue by basxto** [tgxn/lemmy-explorer#138]
**What do you want to see?**
Being able to sort by column in /instance/*/communities

**Comment by tgxn** [comment]
yeah agreed, i kind of hacked that view in last minute to get something usable, the list views all need more advanced sorting.

**Comment by tgxn** [comment]
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/95183829-7e4b-4103-901d-e5dbb20f1be8)

i just made it so it uses the same view as the main communities list... removed the instances filter box :D
