### ISSUE TITLE
Bug: Community list for `lemmy.world` returns for all page numbers

### ISSUE THREAD

**Issue by tgxn** [tgxn/lemmy-explorer#139]
**Describe the bug**

this should obviously return `[]`...
https://lemmy.world/api/v3/community/list?limit=50&page=1220000&type_=Local&show_nsfw=true

**Comment by tgxn** [comment]
This causing issues as the scan never finishes 🤧

all pages after a valid one, seem to return the first pages results?

https://lemmy.ml/api/v3/community/list?limit=50&page=1000034234&type_=Local&show_nsfw=true
returns as expected

**Comment by tgxn** [comment]
Weird issue, I've reached out to lemmy.world admin, and for now scans of lemmy.world are disabled.

**Comment by tgxn** [comment]
They are still having these issues :| I did a bit more digging, and CF is responding with `DYNAMIC` - so this should mean that the response is coming directly from their backend, which would indicate a possible misconfiguration on their backend proxy/load balancing infrastructure. :/

I am thinking I could run a "special" hacky scan for Lemmy.world to retrieve only the first 100 pages from their instance, as that is all that seems to be returned successfully...

It means we'll get random communities, but at least it's something 🤷‍♂️

**Comment by freamon** [comment]
I wondered if you'd have to resort to something hacky. Did you not get a sense from the LW admin that they're willing/able to fix the issue?

There's a lot of junk communities on LW, but the LemmyVerse seems half-empty without it, so I hope something is able to be done (even if it means you hacking it).

**Comment by Mereo** [comment]
> There's a lot of junk communities on LW, but the LemmyVerse seems half-empty without it, so I hope something is able to be done (even if it means you hacking it).

Indeed. I'm currently finding lemmyverse less useful because lemmy.world communities are not listed.

**Comment by tgxn** [comment]
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/8c498532-e05c-4c02-a277-a0e416a73e8d)

we're back in action for now :D I'll close this once the lemmy world communities come back :D

**Comment by tgxn** [comment]
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/be5d3cc8-c4e0-4eec-9ec6-17c2444b9a09)

![image](https://github.com/tgxn/lemmy-explorer/assets/293107/82f6d10f-c1cd-4d43-98c0-75e849ba8f41)

We're back!
