### ISSUE TITLE
Private instance marked as suspect for non-suspect reasons

### ISSUE THREAD

**Issue by irdc** [tgxn/lemmy-explorer#140]
I’m the person behind derp.foo. Much to my surprise it’s being marked as suspect, with the reason being:

	Total Activity vs. Total Users is HIGH: 4678 / 4 = 1169.5 

I happen to host https://derp.foo/c/hackernews, which is likely skewing the statistics. Any chance to get this fixed?

**Comment by tgxn** [comment]
I made a patch to remove the check that's catching your instance, i've improved the checking a bit lately so this one shouldn't be required anymore.

**Comment by tgxn** [comment]
this is resolved 👍
