### ISSUE TITLE
Bug: Checking "Show NSFW" only shows NSFW communities. 

### ISSUE THREAD

**Issue by K4LCIFER** [tgxn/lemmy-explorer#147]
**Describe the bug**
If you heck the box enabling "Show NSFW", *only* NSFW communities will be displayed in the list

**To Reproduce**
1. Ensure that you have instances with non-NSFW content, as well as instances with NSFW content enabled
2. Check "Show NSFW"
3. Observe that *only* NSFW communities are listed, and no non-NSFW communities.

**Expected behavior**
I would expect both NSFW and non-NSFW communities are listed when I click "Show NSFW". If it is intended to be only NSFW, then the text should instead say "Show only NSFW", and you should have an option to show both.

**Additional context**
None.

**Comment by tgxn** [comment]
yeah, the box atm works as a three-stage toggle
1- nsfw off
2- nsfw included
3 - nsfw only

i want to add a confirmation before showing nsfw, along with more obvious wording when you change it...
