### ISSUE TITLE
Feature: Take advantage of the fediseer tags

### ISSUE THREAD

**Issue by db0** [tgxn/lemmy-explorer#148]
**What do you want to see?**
The Fediseer recently added self-tagging functionality, where instance admins can specify some tags that represent their instance

The lemmy explorer could utilize these tags to allow for easier filtering and finding appropriate communities

For example, all the `ttrpg` instances
![image](https://github.com/tgxn/lemmy-explorer/assets/296513/4714f79b-21b5-45c8-9945-e2c021320a98)

The `/api/v1/whitelist` endpoint allows to filter by one of more tags

![image](https://github.com/tgxn/lemmy-explorer/assets/296513/634b54b7-2a5b-45a8-8313-8ca6da19121f)

**Comment by tgxn** [comment]
is there an endpoint to retrieve all possible tags, potentially along with the amount of instances using that tag?
would be cool to add a filtering thing with it too

i'll see about adding the tags under the instance details.

**Comment by db0** [comment]
No, but it should be pretty easy to add an endpoint to see all existing tags, sure. Created https://github.com/Fediseer/fediseer/issues/46

**Comment by tgxn** [comment]
is there any specific order to the tags?
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/be23b6ab-6dce-4320-9a1f-22ebb9357d5f)

I can definitely add them all to the instance-view page _(and make a new sub-page for the rest of the fediseer data!)_, i wonder how I could display them on the main page _(other than adding a filter)_

**Comment by db0** [comment]
No, they're unordered (so basically the order they're pulled by postgres)

**Comment by tgxn** [comment]
OoOoo, I can use that to find the most popular tags, and maybe just show them on the main page.. I'll have a play

**Comment by tgxn** [comment]
ok, i'm getting the data from `/tags` and getting 119 results

i've mapped them into an array where i can use the count to rank them
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/b813e6d6-c1b5-4161-aabe-05b347a9d88f)

i noticed that there are several tags that are applied to instances that do not show up in `/tags` api...
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/c5373b39-a827-4ff9-b3ab-979979f353f0)

it would be nice to have standard tags for the hosting location, or a separate field perhaps? that way I can parse that too.

**Comment by tgxn** [comment]
few more discoveries:
- you now have 2k+ "instances" on fediseer, I'm guessing there's other non-lemmy instances in there? would it be possible to filter `/whitelist` byy `software`?
- I might just be able to infer the data for `tags` - based on merged set of tags from fediseer, and my own tags - for `cloudflare` and `cors-permissive` instances.

**Comment by db0** [comment]
> you now have 2k+ "instances" on fediseer, I'm guessing there's other non-lemmy instances in there? would it be possible to filter /v1/whitelist byy software?

Sure. Can you open a feature request?

> i noticed that there are several tags that are applied to instances that do not show up in /tags api...

This is because the tags api is converting all tags to lowercase in order to combine them

**Comment by tgxn** [comment]
I'll open a feature request for the filtering, thanks 👍

**Comment by db0** [comment]
How are the tags implemented btw. I can't figure it out.
