### ISSUE TITLE
Bug:No kbin flagship instance

### ISSUE THREAD

**Issue by FitikWasTaken** [tgxn/lemmy-explorer#150]
**Describe the bug**
When choosing Kbin Magazines option you don't see magazines from the main kbin.social instance, I am pretty sure it's crawler issue, cause I cant see kbin.social neither on https://data.lemmyverse.net/

**To Reproduce**
1. Go to https://lemmyverse.net/kbin/magazines
2. See that there's no kbin.social magazines

**Expected behavior**
It supposed to show all magazines from all instances using kbin software

**Additional context**
It would be great to have a similar feature to "Sort by instance" for kbin magazines too, but that's not what this bug does

**Comment by tgxn** [comment]
hmm, i can see them now; i run those kbin scans less frequently, and they might be dropping from the cache before i get a chance to include them
https://github.com/tgxn/lemmy-explorer/issues/100#issuecomment-1617444934
this is the reaosn why kbin scanning is a bit bad atm, if they have updated their api i might give it another go.

**Comment by tgxn** [comment]
to continue discussion as related to https://github.com/tgxn/lemmy-explorer/issues/119
i'll add a comment that i need to improve the api integration with kbin
