### ISSUE TITLE
Feature: Edit tags ? (email required, use Cloudflare etc..)

### ISSUE THREAD

**Issue by Max-dc** [tgxn/lemmy-explorer#174]
Hi,

I don't know where come from the tags
![tags](https://github.com/tgxn/lemmy-explorer/assets/152865885/10e88d04-316a-4e56-9984-90523625534c)

Like I don't see any location to edit them so I suppose their are fetched from data.lemmyverse.net too ?

is data.lemmyverse.net provide info if the Lemmy instance require email in order to register ? or if the instance is using Cloudflare ?

If yes, do you think it will possible to include them in lemmy-explorer ?
if no, I will get in touch with the folks that contribute to data.lemmyverse.net

Thanks ! (and amazing job BTW !)

**Comment by tgxn** [comment]
ahh, they are fetched from Fediseer :) I should make that more obvious... https://gui.fediseer.com/

The `Cloudflare` tag is added by me, based on the headers returned from the web server.

**Comment by tgxn** [comment]
Also, all data on *.lemmyverse.net sites is maintained by me, the source of the data is one of two places:
- directly from the instance (using the lemmy API)
- from Fediseer (for tags and additional "smart sort" ordering)

**Comment by tgxn** [comment]
I've updated the readme too, lemmie know if you'd like any more information - just reopen this :)

**Comment by Max-dc** [comment]
Thank you @tgxn ,

So do you think it will be possible (one way or another) to list server that require to provide an email address ?
