### ISSUE TITLE
Feature: When linking to fediseer, link to the specific instance on the UI

### ISSUE THREAD

**Issue by db0** [tgxn/lemmy-explorer#175]
**What do you want to see?**
In the instance info ,there's a link to fediseer.com. It might be better to make the link directly to that instance's profile page on fediseer. For example https://gui.fediseer.com/instances/detail/lemmy.dbzer0.com

**Comment by tgxn** [comment]
I've updated the link to point directly at the instance. 👍 https://github.com/tgxn/lemmy-explorer/pull/178/files#diff-19aa194c2ba30bdf5059895944ad61937b8fb7859e5d9a39848d352cf99cc2d7

**Comment by tgxn** [comment]
closed in #179
