### ISSUE TITLE
Bug: Lemmy instances on 0.19.4 are no longer included

### ISSUE THREAD

**Issue by freamon** [tgxn/lemmy-explorer#184]
### Possible cause:

From what I can understand of this crawler's code, it looks for "http://nodeinfo.diaspora.software/ns/schema/2.0" in the response to /.well-known/nodeinfo

Lemmy 0.19.4 included a change to only provide "http://nodeinfo.diaspora.software/ns/schema/2.1". 

Usually, fediverse platforms that provide 2.1 also provide 2.0, so it wouldn't be a problem, but they've apparently decided to make problems (including for themselves) by not doing so.

**Comment by BentiGorlich** [comment]
This is easily circumventable, as most software supporting the nodeinfo schema also supports the `/.well-known/nodeinfo` endpoint to indicate which urls have to be looked at

**Comment by freamon** [comment]
Just realised: there's already a PR at #183 for this.

**Comment by tgxn** [comment]
Sorry about this, I've been away for a little while. :) Let me get on top of this :D

**Comment by tgxn** [comment]
Merged the PR. Gotta deploy it our to the crawler infra, which is currently performing a backup, will probably take another hour. :)

**Comment by tgxn** [comment]
Ok, It's deployed and running. Should have an update in the next update in ~3-4 hours :)

**Comment by tgxn** [comment]
Hmm, it's scanned the backlog again but not making a huge dent in the un-scannable instances.
Will have to investigate further.

**Comment by tgxn** [comment]
Ok, it's ripping through them now, should be good shortly :D

**Comment by tgxn** [comment]
And yeah it's pretty obvious 0.19.4 has broken it :D

https://lemmyverse.net/inspect/versions

**Comment by tgxn** [comment]
OK, I'm goign to close this. They have started rolling in, though may take another ~12 hours before they all flow through :)
