### ISSUE TITLE
Bug: Programming.Dev instance missing

### ISSUE THREAD

**Issue by Ategon** [tgxn/lemmy-explorer#188]
**Describe the bug**
When looking at the site I just noticed that the programming.dev instance was missing from all of the data. We havent gone down recently or had anything that would really affect the ability to crawl the site and the instance was prevously shown in the past

**To Reproduce**
1. Go to https://lemmyverse.net/
2. Observe the instances

**Expected behavior**
Instance should show up

**Additional context**
![image](https://github.com/user-attachments/assets/cacc940f-034d-418d-b496-62f6b91c6c2f)

**Comment by tgxn** [comment]
Thanks for reporting :)

I've just pushed a new release that should fix it - the data was just 12 days old and not updating because of `docker-compose` no longer existing https://github.com/actions/runner-images/commit/582bbb9c159ff592869037a139124e4bc5e29432

**Comment by tgxn** [comment]
looks like it's back
https://lemmyverse.net/instance/programming.dev/communities

it sometimes takes a while for caches' to empty
