### ISSUE TITLE
[Feature Request] Allow selecting of a "home" instance and show appropriate URLs to other communities

### ISSUE THREAD

**Issue by neoKushan** [tgxn/lemmy-explorer#31]
One of the biggest issues with Lemmy right now is that it's not easy to browse communities from other instances and subscribe to them in one-click. More often than not you can only browse an instance's communities directly from that instance, in which case you have to copy the `!community@lemmy.instance` identifier and search for it on your home instance. It's quite a chore. 

This site is wonderful for searching and browsing other instances and communities, but it suffers the same problem - you have to do the copy->paste->search dance to join the communities displayed.

Ideally, you should be able to pick whatever your home instance is (Or even just type in the base URL) and all of the various urls will be displayed as the `https://my.home.instance/c/community@lemmy.instance` format instead of just the `!community@lemmy.instance` format. 

It'd be a simple change but make finding and joining new communities 2 clicks instead of several.

**Comment by jason-watkins** [comment]
Closely related to this feature would be the ability to search for communities on your own instance easily, since communities that no one has subscribed to on your community yet will give an error message even if the link is correct.

**Comment by L3v3L** [comment]
I created this bookmarklet, maybe you can extract some code to use in this feature:
```js
javascript: (function () {      
    let instance = 'https://lemmy.pt';     
    let urlencoded = encodeURIComponent(window.location.href);     
    window.location.href = `${instance}/search/q/${urlencoded}/type/All/sort/TopAll/listing_type/All/community_id/0/creator_id/0/page/1`; 
})();
```

(note: the final url is to the search page instead of the direct community on the instance because it might not be synced up yet, searching triggers the initial sync up)

**Comment by tgxn** [comment]
> Or even just type in the base URL

this was done in #41 


> able to pick whatever your home instance

This will be done in #5
