### ISSUE TITLE
Provide an option to filter communities to show only NSFW communities

### ISSUE THREAD

**Issue by ppptan** [tgxn/lemmy-explorer#34]

**Comment by tgxn** [comment]
At the moment, the NSFW filter is a bit rough.
I can def make a change to the checkbox to "allow all", "show only nsfw" and "hide only nsfw".

**Comment by tgxn** [comment]
three options checkbox:

![image](https://github.com/tgxn/lemmy-explorer/assets/293107/ee95518e-0c1e-4b55-b9a8-31c111f981fa)
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/0df56dd4-763d-44f2-866a-90c5cb739c49)
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/2f4b81c2-d51a-4c77-8d60-82f283257ac0)

**Comment by ppptan** [comment]
Thanks!
