### ISSUE TITLE
Certain communities does not show up on search bar

### ISSUE THREAD

**Issue by dtantono** [tgxn/lemmy-explorer#38]
Hi 
I tried to search certain communities like https://lemmy.ml/c/bitwarden or https://lemmy.world/c/nvidia . But, it does not show up. Is it a bug?
![image](https://github.com/tgxn/lemmy-explorer/assets/29157187/dc5dcef4-c149-487d-a390-3416bc2ec9b0)
![image](https://github.com/tgxn/lemmy-explorer/assets/29157187/087009de-607f-48ef-b835-2f6f3998b5eb)

**Comment by tgxn** [comment]
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/7f957936-7deb-4815-9744-f250ed055d9f)
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/11c311c6-8c47-40ec-b096-12764980c967)

it's just some outdated data. :)
site updated, i can see them now
