### ISSUE TITLE
[Feature Request] Display/grab lemmy version in instance search

### ISSUE THREAD

**Issue by boomboxnation** [tgxn/lemmy-explorer#39]
It would be nice to see the version of lemmy running on an instance to gain a general idea of the maintainer's interest level.

**Comment by tgxn** [comment]
Added Attribute Tracking in #61

This will let me track changes in certain attributes over time, such as the instance version.

**Comment by tgxn** [comment]
added to list view for instances.

**Comment by boomboxnation** [comment]
Thank You!
