### ISSUE TITLE
[Feature Request] Add Universal Link to open remote communities in a user's home instance

### ISSUE THREAD

**Issue by kringger** [tgxn/lemmy-explorer#40]
Add a Universal Link option in the format of /c/community@instance.tld so that communities will automatically open in the user's home instance.

Currently there are 2 options on a community listing:

1. A url to the community's home instance
2. A quick copy function for !community@instance.tld

The first is great for locating a community's source, but bad if the community is located on an instance other than your home instance.

The second is a remedy for the first's issue, allowing a user to copy the community string so they can place it in their home instance's search field

My recommended 3rd option would skip over the copy/paste step mandatesld by option no.2 , and allow the user to immediately open the remote community in their home instance.  After which, the user can just press subscribe.

**Comment by tgxn** [comment]
Related to #5 - Lemmy SDK Integration

I want to allow users to enter or choose their "home instance", and potentially even login.
This would mean the URL from point 1. would be a link to perhaps:
- https://INSTACNE/c/selfhosted@lemmy.world _(might not exist on their instance)_
- https://INSTACNE/search/q/!selfhosted%40lemmy.world/type/Communities/sort/TopAll/listing_type/All/community_id/0/creator_id/0/page/1 _(would result in a potentially blank search while their instance loads the community)_

I think a better option would be to see if we can use the JS library client-side to pull the instance's communities and what the user is already subscribed to. (maybe I can also perform searches automatically?)

**Comment by tgxn** [comment]
this is merged, closing... i also debounced it in #33
