### ISSUE TITLE
Allow filtering for communities which are officially endorsed failovers from reddit

### ISSUE THREAD

**Issue by db0** [tgxn/lemmy-explorer#43]
This way someone who wants to find which community a subreddit migrated to, they can easily pinpoint it. 

Official lists are being compiled in places like: https://www.quippd.com/writing/2023/06/15/unofficial-subreddit-migration-list-lemmy-kbin-etc.html

Also allow filtering by reddit community. So I can search for "/r/piracy" and find `!piracy@lemmy.dbzer0.com`

**Comment by tgxn** [comment]
I had a think about this, and this isn't really the purpose of this list. I feel that communities are free to put "/r/piracy" in their description, which will be searchable.

It could be handy to have a curated list of communities, but I'm not looking to maintain anything manually.

Maybe there's a future place for adding lists via GitHub `json` files or something to enable list sharing, but there'd be a lot of leg-work to implement this, and I think the feature is better served by existing pages/lists.

**Comment by tgxn** [comment]
Can also look at this list https://sub.rehab/

![image](https://github.com/tgxn/lemmy-explorer/assets/293107/64ce0a5e-6bb5-4a9b-a548-ef4422edb2d9)
