### ISSUE TITLE
Communites affected by the remote moderator bug are not showing in search results.

### ISSUE THREAD

**Issue by kringger** [tgxn/lemmy-explorer#48]
Hi, the following bug is making it so affected communities are not showing in search results.

https://github.com/LemmyNet/lemmy/issues/3075

For example, the community https://lemmy.ml/c/ps5 no longer shows in search results as the site now returns a 404.

Until the bug is fixed in the next backend update, this community can only be found at https://lemmy.ml/c/ps5@lemmy.ml

Other communities are affected by this as well.

**Comment by tgxn** [comment]
Looks like they also don't show up in the communities list for "Local", and because the crawler uses that in the query, they don't get returned.

https://github.com/tgxn/lemmy-explorer/blob/main/crawler/src/crawl/community.js#L52

Not much I can do really, I could scan all communities, but it'd be a significantly larger request.

**Comment by kringger** [comment]
If it is feasible, I think scanning all communities until the issue is fixed would help those afflicted. Discoverability is a real issue with Lemmy right now, and I'm sure the afflicted communities would greatly appreciate it. 

I totally understand if it is too much though. I just noticed the issue and thought to make you aware of it so see if there was an easy fix.

**Comment by tgxn** [comment]
Thanks for letting me know! I am keeping an eye on that issue, and hopefully lemmy.ml apply the patch soon!

I had a look, and the "Local" communities currently runs to about ~60 pages of 50 items, if I pushed for non-Local, that'd likely go up to well over 200 requests.

Not really feasible to do this many pages; as even the current ~60 pages sometimes has errors half way through.

I'm gonna close this for now 👍
