### ISSUE TITLE
Feature request: Setting for Lemmy instance to open

### ISSUE THREAD

**Issue by burtek** [tgxn/lemmy-explorer#50]
Currently the lemmy communities open on their respective instances upon clicking. It would be great if user was able to provide their instance of choice to open all communities in, so that upon clicking on `!community@lemmy.server` the website would open with URL `users-lemmy-instance.tld/c/community@lemmy.server` rather than `lemmy.server/c/community`

Happy to create a PR for that today or tomorrow.

**Comment by tgxn** [comment]
It's already done 🤔

![image](https://github.com/tgxn/lemmy-explorer/assets/293107/24b6ab38-6b21-4335-a581-148f02b4aba0)
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/f5b162b8-fe4f-4cc8-beca-899b151273b5)

**Comment by burtek** [comment]
Missed that! Thanks ❤️

**Comment by burtek** [comment]
Where do I find this on mobile though?

![Screenshot_20230618_102224_Firefox.png](https://github.com/tgxn/lemmy-explorer/assets/2940958/86aa3d94-16f5-40f2-a31f-031346e61cde)

**Comment by burtek** [comment]
Ok, found it on home page.

**Comment by tgxn** [comment]
No worries, some times it can take a little while to roll out :)
