### ISSUE TITLE
Negative search terms in community search

### ISSUE THREAD

**Issue by ppptan** [tgxn/lemmy-explorer#59]
e.g. a search like "cats -dogs" will show communities that have "cats" in their searchable fields, filtering out communities that have "dogs" in their searchable fields.

**Comment by tgxn** [comment]
Great idea!

Example Searches that should work:
"piracy -news"
"orange cat -braincell"
"-dogs cats" === "cats -dogs"
"playstation 5 -cats" - ie. should match full string

My thinking:
- split the search query on " " (space)
- find any query elements that start with `-` (minus)
- recombine search query without `-` items
- apply search as:
  - apple search as before
  - remove items that contains items prefixed with `-`

**Comment by ppptan** [comment]
Quick work!
