### ISSUE TITLE
Export JSON or CSV

### ISSUE THREAD

**Issue by retiolus** [tgxn/lemmy-explorer#68]
Is there a way to export data (instances or communities lists) to a JSON or other format file?

**Comment by tgxn** [comment]
The latest JSON files are here (from my data) 
https://github.com/tgxn/lemmy-explorer/tree/main/frontend/public

They are stored alongside the application in AWS, but I'd prefer if people hotlinked/downloaded the JSONs from GitHub as I don't pay for bandwidth :D

The latest run was:
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/1d5d31dc-3292-4ce9-b9f2-57766295142b)

Re-open is there's anything else :)
