### ISSUE TITLE
Error when filtering instances or communities

### ISSUE THREAD

**Issue by Tywele** [tgxn/lemmy-explorer#69]
I had to open the site in incognito mode because I couldn't access it anymore because of this bug.

As soon as I start typing in the filter input field the website turns completely white (blank) and I get this error in the console:
```
Uncaught ReferenceError: retinstancesurn is not defined
    e https://lemmyverse.net/bundle.js:5
    T https://lemmyverse.net/bundle.js:5
    T https://lemmyverse.net/bundle.js:5
    Ki https://lemmyverse.net/bundle.js:2
    useMemo https://lemmyverse.net/bundle.js:2
    Sb https://lemmyverse.net/bundle.js:5
    xi https://lemmyverse.net/bundle.js:2
    Ls https://lemmyverse.net/bundle.js:2
    Ml https://lemmyverse.net/bundle.js:2
    yu https://lemmyverse.net/bundle.js:2
    gu https://lemmyverse.net/bundle.js:2
    vu https://lemmyverse.net/bundle.js:2
    au https://lemmyverse.net/bundle.js:2
    ou https://lemmyverse.net/bundle.js:2
    S https://lemmyverse.net/bundle.js:2
    Y https://lemmyverse.net/bundle.js:2
```

As soon as I got this error I was unable to revert to the site without filtering. Deleting cookies didn't help. Only opening it in an incognito tab.

![grafik](https://github.com/tgxn/lemmy-explorer/assets/8156875/5f1e6c54-80c6-435f-8b8a-8860ea58062a)

**Comment by tgxn** [comment]
I might've broken it 😱

**Comment by tgxn** [comment]
It's pushed :) Thanks for letting me know @Tywele !
