### ISSUE TITLE
Can we flag https://lemmit.online/ as as suspicious instance? 

### ISSUE THREAD

**Issue by M4rtineski** [tgxn/lemmy-explorer#75]
Can we flag https://lemmit.online/ as a suspicious instance? It's an instance run by a bot and it mass reposts stuff from reddit which is basically spam. I don't want to see communites from this instance while searching for sublemmies because sublemmies on this instance are VERY LOW quality and you won't get any engagement when you do interact with those communities by commenting on stuff.

Or could we at least get an option to block choosen instances by ourselves so user can decide what he doesn't want to see?

**Comment by tgxn** [comment]
This one should be added to my suspicious instances filter
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/0e51f675-6683-4141-a0ce-b482fd6bed00)

Can see that the posts is far greater than what we'd expect for that user count.

**Comment by tgxn** [comment]
Update to site in progress now.

Sus instances can still be viewed by turning them on
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/b3a9d6c2-6316-42a3-9497-4c674e1548c5)

**Comment by M4rtineski** [comment]
Thanks
