### ISSUE TITLE
Communities vanishing from the browser

### ISSUE THREAD

**Issue by ParsnipWitch** [tgxn/lemmy-explorer#83]
Hi!

There seems to be an issue with the community browser where some communities get removed although they still exist on the instance. 

I am not sure if this problem is with the specific Lemmy instance, the specific community or the lemmyverse browser and I am not sure how to troubleshoot it.

The community is feddit.de/c/cozygames.
It definitely did appear on the browser  before. 

Other communities from the feddit instance are still able to be found with your browser. On feddit I can find the community when I look for "local" or "all" communities.

Thank you so much and I hope this is posted to the correct place. :)

**Comment by tgxn** [comment]
Hmm, it seems to show up for me?
https://lemmyverse.net/communities?query=cozygames

**Comment by tgxn** [comment]
feddit.de/c/cozygames was last scanned `Saturday, 24 June 2023 6:34:20.289 AM` which is a week ago, and it's not getting returned in the latest...
![image](https://github.com/tgxn/lemmy-explorer/assets/293107/a61dbc05-aaa8-43bf-99f7-992f3380f118)

**Comment by tgxn** [comment]
I created a checker that goes thru the ages communities and updates or deletes them. Should fix this kinda thing going forward...

https://lemmyverse.net/communities?query=cozy+games
![Uploading image.png…]()
