### ISSUE TITLE
Lemmy instance not showing on list

### ISSUE THREAD

**Issue by chenew** [tgxn/lemmy-explorer#88]
Hello! I stood up a Lemmy instance on June 25th. I’ve been checking for a few days and it hasn’t shown up here yet. Is there anything I need to do on the server for the crawler to discover it? Instance name is techy.news. Thank you!

**Comment by tgxn** [comment]
What's your community's hostname / address?

**Comment by tgxn** [comment]
New version published:
https://lemmyverse.net/instance/techy.news

https://github.com/tgxn/lemmy-explorer#faq

more to come :)

**Comment by chenew** [comment]
@tgxn Thank you!!
